#!/usr/bin/env node
/**
 * Coding Sub-Agent
 * ================
 * A minimal A2A-compliant HTTP server that acts as a "coding assistant"
 * sub-agent in the a2a-subagents-scenario example.
 *
 * What it does
 * ------------
 * - Serves an A2A agent card at  GET /.well-known/agent-card.json
 * - Handles A2A JSON-RPC calls at POST /a2a/jsonrpc
 * - Exposes two skills: `review` and `explain`
 *
 * The responses are deterministic stubs — no LLM is involved. This
 * makes the agent perfect for integration tests and demos: it always
 * responds instantly and predictably.
 *
 * Usage
 * -----
 *   node agents/coding-agent.mjs [port]
 *   # default port: 4101
 *
 * The agent card URL (used in parent/config.json) is:
 *   http://127.0.0.1:<port>/.well-known/agent-card.json
 */

import http from "node:http";

const PORT = Number(process.argv[2] ?? 4101);
const BASE_URL = `http://127.0.0.1:${PORT}`;

// ─── Agent Card ──────────────────────────────────────────────────────────────
// This is what a2a-mcp-skillmap fetches to discover the agent's skills.
// Each skill becomes one MCP tool: coding__review, coding__explain.

const AGENT_CARD = {
  protocolVersion: "0.3.0",
  name: "coding",
  description:
    "A coding assistant that reviews code for issues and explains what code does.",
  version: "1.0.0",
  url: `${BASE_URL}/a2a/jsonrpc`,
  preferredTransport: "JSONRPC",
  defaultInputModes: ["text"],
  defaultOutputModes: ["text"],
  capabilities: { streaming: false, pushNotifications: false },
  skills: [
    {
      id: "review",
      name: "Code Review",
      description:
        "Review a code snippet and return a list of issues, suggestions, and an overall quality score.",
      tags: ["code", "review", "quality"],
      examples: ["Review this Python function for bugs", "What's wrong with this SQL query?"],
    },
    {
      id: "explain",
      name: "Code Explanation",
      description:
        "Explain what a piece of code does in plain English, suitable for non-technical stakeholders.",
      tags: ["code", "explain", "documentation"],
      examples: ["Explain this regex", "What does this shell script do?"],
    },
  ],
};

// ─── Stub Responses ──────────────────────────────────────────────────────────
// Real agents would call an LLM here. We return deterministic stubs so
// the scenario test is fast, offline, and reproducible.

function handleSkill(skillId, message) {
  const text = typeof message === "string" ? message : JSON.stringify(message);

  if (skillId === "review") {
    return {
      kind: "text",
      text: [
        `[coding-agent / review] Reviewed: "${text.slice(0, 80)}..."`,
        "",
        "Issues found:",
        "  • No issues detected in this stub response.",
        "  • In a real deployment this would call an LLM.",
        "",
        "Quality score: 9/10",
      ].join("\n"),
    };
  }

  if (skillId === "explain") {
    return {
      kind: "text",
      text: [
        `[coding-agent / explain] Explanation for: "${text.slice(0, 80)}..."`,
        "",
        "This code performs the requested operation. In a real deployment",
        "this response would be generated by an LLM with full context.",
      ].join("\n"),
    };
  }

  return { kind: "text", text: `[coding-agent] Unknown skill: ${skillId}` };
}

// ─── A2A JSON-RPC Handler ────────────────────────────────────────────────────

function handleJsonRpc(body) {
  let req;
  try {
    req = JSON.parse(body);
  } catch {
    return { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } };
  }

  const taskId = `coding-task-${Date.now()}`;

  // Extract the user message text from the A2A message/send payload.
  const parts = req.params?.message?.parts ?? [];
  const textPart = parts.find((p) => p.kind === "text" || p.type === "text");
  const messageText = textPart?.text ?? JSON.stringify(req.params);

  // Determine which skill was invoked from the method or params.
  // a2a-mcp-skillmap routes calls to the agent's JSON-RPC endpoint;
  // the skill is encoded in the message or can be inferred from context.
  const skillHint = (req.params?.metadata?.skillId ?? req.method ?? "explain").toLowerCase();
  const skillId = skillHint.includes("review") ? "review" : "explain";

  const artifact = handleSkill(skillId, messageText);

  return {
    jsonrpc: "2.0",
    id: req.id ?? null,
    result: {
      kind: "task",
      id: taskId,
      contextId: `ctx-${taskId}`,
      status: {
        state: "completed",
        timestamp: new Date().toISOString(),
      },
      artifacts: [
        {
          artifactId: `${taskId}-artifact`,
          name: "response",
          parts: [artifact],
        },
      ],
    },
  };
}

// ─── HTTP Server ─────────────────────────────────────────────────────────────

const server = http.createServer((req, res) => {
  const ts = new Date().toISOString();
  console.log(`[coding-agent] ${ts}  ${req.method} ${req.url}`);

  // Agent card — the primary discovery endpoint.
  if (req.method === "GET" && req.url === "/.well-known/agent-card.json") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify(AGENT_CARD, null, 2));
    return;
  }

  // Health check — useful for monitoring and the startup probe.
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "ok", agent: "coding", port: PORT }));
    return;
  }

  // A2A JSON-RPC endpoint.
  if (req.method === "POST" && req.url === "/a2a/jsonrpc") {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      const response = handleJsonRpc(body);
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(response));
    });
    return;
  }

  res.writeHead(404, { "Content-Type": "text/plain" });
  res.end("Not found");
});

server.listen(PORT, "127.0.0.1", () => {
  console.log(`[coding-agent] Listening on ${BASE_URL}`);
  console.log(`[coding-agent] Agent card: ${BASE_URL}/.well-known/agent-card.json`);
  console.log(`[coding-agent] Skills: coding__review, coding__explain`);
  console.log(`[coding-agent] Press Ctrl+C to stop.`);
});
