#!/usr/bin/env node
/**
 * Research Sub-Agent
 * ==================
 * A minimal A2A-compliant HTTP server that acts as a "research assistant"
 * sub-agent in the a2a-subagents-scenario example.
 *
 * What it does
 * ------------
 * - Serves an A2A agent card at  GET /.well-known/agent-card.json
 * - Handles A2A JSON-RPC calls at POST /a2a/jsonrpc
 * - Exposes two skills: `search` and `summarize`
 *
 * The responses are deterministic stubs — no LLM or external API is
 * involved. This makes the agent perfect for integration tests and demos.
 *
 * Usage
 * -----
 *   node agents/research-agent.mjs [port]
 *   # default port: 4102
 *
 * The agent card URL (used in parent/config.json) is:
 *   http://127.0.0.1:<port>/.well-known/agent-card.json
 */

import http from "node:http";

const PORT = Number(process.argv[2] ?? 4102);
const BASE_URL = `http://127.0.0.1:${PORT}`;

// ─── Agent Card ──────────────────────────────────────────────────────────────
// Each skill becomes one MCP tool: research__search, research__summarize.

const AGENT_CARD = {
  protocolVersion: "0.3.0",
  name: "research",
  description:
    "A research assistant that searches for information and summarizes documents.",
  version: "1.0.0",
  url: `${BASE_URL}/a2a/jsonrpc`,
  preferredTransport: "JSONRPC",
  defaultInputModes: ["text"],
  defaultOutputModes: ["text"],
  capabilities: { streaming: false, pushNotifications: false },
  skills: [
    {
      id: "search",
      name: "Web Search",
      description:
        "Search for information on a topic and return a list of relevant findings with sources.",
      tags: ["research", "search", "web"],
      examples: ["Search for recent papers on LLM agents", "Find information about A2A protocol"],
    },
    {
      id: "summarize",
      name: "Document Summarizer",
      description:
        "Summarize a long document or article into key points and a one-paragraph executive summary.",
      tags: ["research", "summarize", "nlp"],
      examples: ["Summarize this research paper", "Give me the key points from this article"],
    },
  ],
};

// ─── Stub Responses ──────────────────────────────────────────────────────────

function handleSkill(skillId, message) {
  const text = typeof message === "string" ? message : JSON.stringify(message);

  if (skillId === "search") {
    return {
      kind: "text",
      text: [
        `[research-agent / search] Results for: "${text.slice(0, 80)}..."`,
        "",
        "Top findings:",
        "  1. Finding A — This is a stub result. Real deployment calls a search API.",
        "  2. Finding B — Another stub result with a plausible-looking source.",
        "  3. Finding C — Third result for completeness.",
        "",
        "Sources: [stub-source-1.example.com, stub-source-2.example.com]",
      ].join("\n"),
    };
  }

  if (skillId === "summarize") {
    return {
      kind: "text",
      text: [
        `[research-agent / summarize] Summary of: "${text.slice(0, 80)}..."`,
        "",
        "Key points:",
        "  • The document covers the requested topic in detail.",
        "  • Several important conclusions are drawn.",
        "  • Further reading is recommended.",
        "",
        "Executive summary: This is a stub summary. In a real deployment",
        "this would be generated by an LLM with the full document as context.",
      ].join("\n"),
    };
  }

  return { kind: "text", text: `[research-agent] Unknown skill: ${skillId}` };
}

// ─── A2A JSON-RPC Handler ────────────────────────────────────────────────────

function handleJsonRpc(body) {
  let req;
  try {
    req = JSON.parse(body);
  } catch {
    return { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } };
  }

  const taskId = `research-task-${Date.now()}`;

  const parts = req.params?.message?.parts ?? [];
  const textPart = parts.find((p) => p.kind === "text" || p.type === "text");
  const messageText = textPart?.text ?? JSON.stringify(req.params);

  const skillHint = (req.params?.metadata?.skillId ?? req.method ?? "search").toLowerCase();
  const skillId = skillHint.includes("summar") ? "summarize" : "search";

  const artifact = handleSkill(skillId, messageText);

  return {
    jsonrpc: "2.0",
    id: req.id ?? null,
    result: {
      kind: "task",
      id: taskId,
      contextId: `ctx-${taskId}`,
      status: {
        state: "completed",
        timestamp: new Date().toISOString(),
      },
      artifacts: [
        {
          artifactId: `${taskId}-artifact`,
          name: "response",
          parts: [artifact],
        },
      ],
    },
  };
}

// ─── HTTP Server ─────────────────────────────────────────────────────────────

const server = http.createServer((req, res) => {
  const ts = new Date().toISOString();
  console.log(`[research-agent] ${ts}  ${req.method} ${req.url}`);

  if (req.method === "GET" && req.url === "/.well-known/agent-card.json") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify(AGENT_CARD, null, 2));
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "ok", agent: "research", port: PORT }));
    return;
  }

  if (req.method === "POST" && req.url === "/a2a/jsonrpc") {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      const response = handleJsonRpc(body);
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify(response));
    });
    return;
  }

  res.writeHead(404, { "Content-Type": "text/plain" });
  res.end("Not found");
});

server.listen(PORT, "127.0.0.1", () => {
  console.log(`[research-agent] Listening on ${BASE_URL}`);
  console.log(`[research-agent] Agent card: ${BASE_URL}/.well-known/agent-card.json`);
  console.log(`[research-agent] Skills: research__search, research__summarize`);
  console.log(`[research-agent] Press Ctrl+C to stop.`);
});
